package com.MessTech.common.material;

import com.MessTech.init.MessTech;

import gregtech.api.enums.Dyes;
import gregtech.api.enums.MaterialBuilder;
import gregtech.api.enums.MaterialIconRegistry;
import gregtech.api.enums.Materials;
import gregtech.api.enums.TextureSet;
import gregtech.api.enums.Textures;
import gregtech.api.enums.TierEU;
import gregtech.api.interfaces.IMaterialHandler;

/**
 * The Chaos Matter material (混乱物质): one ingot that is every alloy and element GregTech knows, stirred together.
 * <p>
 * It is a normal GregTech material, so GT itself provides the items: {@code MetaGeneratedItem01} walks
 * {@code GregTechAPI.sGeneratedMaterials} and turns the METAL/DUST/GEAR generation bits into the ingot, its dusts,
 * plates, gears and the ore dictionary entries, and the item's look comes from {@code Materials.renderer} - see
 * {@link com.MessTech.common.render.MTChaosMatterRenderer}.
 * <p>
 * <b>Registration timing.</b> GT runs {@code Materials.init()} in its own preInit, which happens before this mod's
 * preInit, so the handler must be added from the {@code @Mod} constructor ({@link #register()}) - at that point no
 * preInit has run at all. {@code IMaterialHandler#onMaterialsInit} is then called from inside
 * {@code Materials.init()}, right after {@code MaterialsIDMap} gave every GT material its {@code mMetaItemSubID} and
 * before the material list is frozen, which is the only moment a material and its id can still be added.
 * <p>
 * <b>Material id.</b> {@code MaterialsIDMap} is GT's hardcoded 0..999 id table and has no "take a free id" API for
 * addons, so {@link #findFreeId()} takes the <b>middle of the widest run of unused ids</b> inside
 * {@value #ID_SCAN_MIN}..{@value #ID_SCAN_MAX}: GT keeps roughly the same amount of room on both sides of us, and
 * the top of the band - where GT registers its newest materials (Infinity, SpaceTime, the Halkonites) - is left
 * untouched on purpose. A run shorter than {@value #ID_MIN_FREE_RUN} ids is never taken, so a single hole in GT's
 * table is not squatted either.
 */
public final class MTChaosMatter {

    private MTChaosMatter() {}

    /** Internal material name. The display name is the lang key {@code Material.chaosmatter}. */
    public static final String NAME = "ChaosMatter";

    /** Local name used where the lang file has no entry. */
    public static final String DEFAULT_LOCAL_NAME = "Chaos Matter";

    /** Texture domain of the icons: {@code assets/messtech/textures/items/materialicons/chaos/}. */
    public static final String TEXTURE_DOMAIN = "messtech";

    /** Texture set name, which is also the folder under {@code materialicons/}. */
    public static final String TEXTURE_SET = "chaos";

    /**
     * Ids are only taken from this band: below it sit the elements and the oldest alloys, above it GT's newest
     * materials. The band and the minimum run length are what "leave GT room for its own registrations" means here.
     */
    private static final int ID_SCAN_MIN = 100;
    private static final int ID_SCAN_MAX = 949;
    private static final int ID_MIN_FREE_RUN = 8;

    /** The registered material, or null before GT's {@code Materials.init()} ran. */
    private static Materials material;

    /** Adds the material handler. Must be called from the {@code @Mod} constructor, see the class javadoc. */
    public static void register() {
        Materials.add(new ChaosMatterHandler());
    }

    /** The registered material, or null before GT's {@code Materials.init()} ran. */
    public static Materials getMaterial() {
        return material;
    }

    private static final class ChaosMatterHandler implements IMaterialHandler {

        @Override
        public void onMaterialsInit() {
            Materials created = new MaterialBuilder().setName(NAME)
                .setDefaultLocalName(DEFAULT_LOCAL_NAME)
                // The formula of a material that is every material at once.
                .setChemicalFormula("*")
                .setIconSet(chaosTextureSet())
                .setColor(Dyes.dyeLightGray)
                // Light grey: the icons are modulated with this colour, so the chaos of the art survives the tint.
                .setARGB(0xFFD8D8D8)
                .setTool(2_621_440, 25, 320.0F)
                .setMeltingPoint(10_800)
                .setBlastFurnaceTemp(10_800)
                .setBlastFurnaceRequired(true)
                // No auto-generated recipes: the material exists, the ways to make it are added deliberately.
                .setAutoGenerateBlastFurnaceRecipes(false)
                .setAutoGeneratedVacuumFreezerRecipe(false)
                .addDustItems()
                .addMetalItems()
                .addGearItems()
                .constructMaterial()
                .setProcessingMaterialTierEU(TierEU.RECIPE_UV);

            IdSlot slot = findFreeId();
            if (slot == null) {
                // Without an id OrePrefixes#doGenerateItem refuses every prefix, so GT would register no items at all
                // and the material would be an invisible entry. Not registering is the honest outcome.
                MessTech.MT_LOG.error(
                    "Chaos Matter: no free material id in {}..{} (at least {} in a row needed) - not registered",
                    ID_SCAN_MIN,
                    ID_SCAN_MAX,
                    ID_MIN_FREE_RUN);
                return;
            }

            created.mMetaItemSubID = slot.id;
            created.mHasParentMod = true;
            material = created;

            MessTech.MT_LOG.info(
                "Chaos Matter: registered as material id {} (widest free run {}..{}, took the middle so GT keeps {} ids below and {} above)",
                slot.id,
                slot.runStart,
                slot.runStart + slot.runLength - 1,
                slot.id - slot.runStart,
                slot.runStart + slot.runLength - 1 - slot.id);
        }
    }

    /** The id that was picked plus the free run it came from, only for the log line. */
    private static final class IdSlot {

        private final int id;
        private final int runStart;
        private final int runLength;

        private IdSlot(int id, int runStart, int runLength) {
            this.id = id;
            this.runStart = runStart;
            this.runLength = runLength;
        }
    }

    /**
     * Middle of the widest run of unused ids inside the scan band, or null when the band has no run long enough.
     * <p>
     * Every GT material already has its id when this runs - {@code MaterialsIDMap#register()} is the first thing
     * {@code Materials.init()} does - so the used ids can be read straight off the material map.
     */
    private static IdSlot findFreeId() {
        boolean[] used = new boolean[1000];
        for (Materials candidate : Materials.getMaterialsMap()
            .values()) {
            int id = candidate.mMetaItemSubID;
            if (id >= 0 && id < used.length) used[id] = true;
        }

        int bestStart = -1;
        int bestLength = 0;
        int currentStart = -1;
        for (int id = ID_SCAN_MIN; id <= ID_SCAN_MAX + 1; id++) {
            boolean free = id <= ID_SCAN_MAX && !used[id];
            if (free) {
                if (currentStart < 0) currentStart = id;
                continue;
            }
            if (currentStart >= 0) {
                int length = id - currentStart;
                if (length > bestLength) {
                    bestLength = length;
                    bestStart = currentStart;
                }
                currentStart = -1;
            }
        }

        if (bestStart < 0 || bestLength < ID_MIN_FREE_RUN) return null;
        return new IdSlot(bestStart + bestLength / 2, bestStart, bestLength);
    }

    /**
     * The chaos texture set. GT's texture sets always read from the {@code gregtech} domain and an addon cannot put
     * files into another mod's domain, so the freshly built set has its (public, element-mutable) texture array
     * rewritten to {@code messtech} containers. A file that does not exist falls back to GT's global {@code NONE}
     * set inside the container itself, so only the icons that were drawn are actually shipped.
     */
    private static TextureSet chaosTextureSet() {
        TextureSet set = new TextureSet(TEXTURE_SET);
        for (MaterialIconRegistry.IconType type : MaterialIconRegistry.IconType.VALUES) {
            // The VOID slots keep GT's shared void icon; there is no file to look for.
            if ("/void".equals(type.suffix)) continue;

            set.mTextures[type.ordinal()] = switch (type.texture) {
                case BLOCK -> Textures.BlockIcons.textureSet(TEXTURE_DOMAIN, TEXTURE_SET, type.suffix);
                case BLOCK_WITH_ALPHA -> Textures.BlockIcons
                    .customAlpha(TEXTURE_DOMAIN, Textures.TextureMaterialIconDirectory + TEXTURE_SET + type.suffix);
                case ITEM -> Textures.ItemIcons.textureSet(TEXTURE_DOMAIN, TEXTURE_SET, type.suffix);
            };
        }
        return set;
    }
}
