
name: Build and test

on:
  pull_request:
    branches: [ master, master-29x-beta2-3, master-2.9.0-beta1 ]
  push:
    branches: [ master, master-29x-beta2-3, master-2.9.0-beta1 ]

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    with:
      timeout: 180
    secrets: inherit

